name: covid_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  image: ^4.1.7
  riverpod_annotation: ^2.3.5
  riverpod: ^2.5.1
  intl: ^0.17.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.4.0

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/responses/



